apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels:
    app: goserver
spec:
#  quando coloca uma label vc pode selecionar labels de acord com uma especificação
  selector: 
    matchLabels:
      app: goserver
  replicas: 2
  # especifica o template do pod
  template:
    metadata:
      labels:
        app: goserver
    spec:
      containers:
        - name: goserver
          image: charles00willian/hello-go:v3.1
          envFrom:
            - configMapRef:
                name: configmap-family
          
          volumeMounts:
            - mountPath: "/go/myfamily"
              name: config

            # criando sem o configMapRef
            # - name: NAME
            #   valueFrom: 
            #     configMapKeyRef:
            #       name: goserver-env
            #       key: NAME
            # - name: AGE
            #   valueFrom: 
            #     configMapKeyRef:
            #       name: goserver-env
            #       key: AGE
      volumes:
        - name: config
          configMap:
            name: configmap-family
            items:
              - key: members
                path: "family.txt"
            