apiVersion: v1
kind: Service
metadata:
  name: goserver-service
spec:
# filtro para selecionar os pods que serão expostos
  selector: 
    app: goserver
  type: ClusterIP
  ports: 
  - name: goserver-service
    # porta do service.
    port: 8000
    # indica qual porta do container será exposta
    targetPort: 80
    protocol: TCP